In [1]:
#Importing Libary

import selenium
import pandas as pd
from selenium import webdriver

import requests
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [2]:
#Driver

driver = webdriver.Chrome(r"C:\Users\shaik mahaboob basha\Downloads\chromedriver.exe")

Write a python program which searches all the product under a particular product from 
www.amazon.in. The product name to be searched will be taken as input from user. For e.g. If 
user input is ‘guitar’. Then search for guitars.

In [52]:
url = 'https://www.amazon.in/' 

driver.get(url)

In [53]:
#entering Inputs in the feild

search_product = driver.find_element_by_id("twotabsearchtextbox").send_keys("Laptop")
search_btn = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span").click()

In [60]:
driver.close()

2. In the above question, now scrape the following details of each product listed in first 3 pages 
of your search results and save it in a dataframe and csv. In case if any product vertical has 
less than 3 pages in search results then scrape all the products available under that product 
vertical. Details to be scraped are: "Brand Name", "Name of the Product", "Rating", "No. of 
Ratings", "Price", "Return/Exchange", "Expected Delivery", "Availability", "Other Details" 
and “Product URL”. In case, if any of the details are missing for any of the product then 
replace it by “-“.

In [6]:
#creating the empty list
Brand_Name=[]
Name_of_the_Product=[]
Ratings=[]
No_of_Ratings=[]
Price=[]
Return_Exchange=[]
Expected_Delivery=[]
Availability=[]
Product_URL=[]

In [5]:
# create dictionary
jobs={"Ratings":[],"No_of_Ratings":[],"Ratings":[]}

In [27]:
#scrapping the required details
start=0
end=3
for page in range(start,end):#for loop for scrapping 3 page
    #scrapping Price
    prices=driver.find_elements_by_xpath("//span[@class='a-price-whole']")
    for i in prices[:100]:
        Price.append(i.text)

In [28]:
 #scrapping No Of Rating
nor=driver.find_elements_by_xpath("//span[@class='a-size-base']")
for i in nor[:100]:
    No_of_Ratings.append(i.text)

In [29]:
 #scrapping Expected Date
Exp_Date=driver.find_elements_by_xpath("//span[@class='a-text-bold']")
for i in Exp_Date[:100]:
    try:
        Expected_Delivery.append(i.text)
    except NoSuchElementException   as e:
        Expected_Delivery.append("NO Expected Date")#appending the No rating if no rating is there

In [48]:
#creating a dataframe
df=pd.DataFrame({'Price':Price[:40],
                 'Ratings':Ratings[:40],
                'No_of_Ratings':No_of_Ratings[:40],
                'Expected_Delivery':Expected_Delivery[:40]})

In [56]:
df

     Price       Ratings No_of_Ratings   Expected_Delivery
0   54,990     NO rating           429    Wednesday, May 5
1   63,990  4.3 out of 5             1       Friday, May 7
2   23,990  4.3 out of 5           104    Wednesday, May 5
3   27,390  3.5 out of 5           292       Friday, May 7
4   27,890  3.5 out of 5            20  Saturday, April 24
5   25,990     NO rating           453    Friday, April 23
6   24,990     NO rating           163   Tuesday, April 27
7   17,990     NO rating           179    Sunday, April 25
8   26,599     NO rating             5  Saturday, April 24
9   24,990     NO rating            38    Friday, April 23
10  61,990     NO rating           144    Friday, April 23
11  53,990     NO rating         1,275    Wednesday, May 5
12  21,990     NO rating             4       Friday, May 7
13  60,990     NO rating            73    Wednesday, May 5
14  31,999     NO rating             7       Friday, May 7
15  35,390     NO rating           429    Friday, April 23
16  46,494     NO rating             1    Sunday, April 25
17  38,790     NO rating           104   Tuesday, April 27
18  27,990     NO rating           292  Saturday, April 24
19  26,990     NO rating            20    Friday, April 23
20  55,990     NO rating           453    Friday, April 23
21  42,990  4.3 out of 5           163    Friday, April 23
22  54,990  4.3 out of 5           179    Friday, April 23
23  63,990  4.4 out of 5             5    Wednesday, May 5
24  23,990  4.4 out of 5            38       Friday, May 7
25  27,390  4.5 out of 5           144    Wednesday, May 5
26  27,890  4.5 out of 5         1,275       Friday, May 7
27  25,990  4.2 out of 5             4    Wednesday, May 5
28  24,990  4.2 out of 5            73       Friday, May 7
29  17,990  4.4 out of 5             7    Wednesday, May 5
30  26,599  4.4 out of 5           429       Friday, May 7
31  24,990  4.2 out of 5             1  Saturday, April 24
32  61,990  4.2 out of 5           104    Friday, April 23
33  53,990  4.4 out of 5           292   Tuesday, April 27
34  21,990  4.4 out of 5            20    Sunday, April 25
35  60,990    4 out of 5           453  Saturday, April 24
36  31,999    4 out of 5           163    Friday, April 23
37  35,390  4.3 out of 5           179    Friday, April 23
38  46,494  4.3 out of 5             5    Wednesday, May 5
39  38,790    4 out of 5            38       Friday, May 7

In [32]:
#scrapping the required details
start=0
end=3
for page in range(start,end):#for loop for scrapping 3 page
    #Scrapping Titles
    titles=driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
    for i in titles[:101]:
        Brand_Name.append(i.text)

In [34]:
data=pd.DataFrame({'Brand_Name':Brand_Name[:40]})
print(data)

                                           Brand_Name
0   (Renewed) Dell Vostro 5401 Laptop|i5-1035G1|8G...
1   (Renewed) Dell G3 3500 Laptop|i5-10300H|8GB DD...
2   HP 15 Entry Level 15.6-inch HD Laptop (AMD 302...
3   Dell Inspiron 3502 15.6" HD Display Laptop (Pe...
4   Lenovo IdeaPad Slim 3 Intel Celeron N4020 15.6...
5   Lenovo Ideapad Slim 3 AMD Athlon Silver 3050U ...
6   ASUS VivoBook 14 (2020) Intel Quad Core Pentiu...
7   AVITA Essential NE14A2INC433-MB 14-inch Laptop...
8   HP 15 Intel Pentium Gold 6405U Processor Entry...
9   HP Chromebook 14a-na0003TU 14-inch Thin & Ligh...
10  (Renewed) Dell G3 3590 Laptop|i5-9300H|8GB DDR...
11  (Renewed) Dell Inspiron 5593 Laptop|i5-1035G1|...
12  Life Digital Entry Level Laptop, (Intel Core i...
13  Lenovo IdeaPad S540 10th Gen Intel Core i5 15....
14  HP 15 Thin & Light Ryzen 3-3250 Laptop, 4 GB R...
15  Dell Vostro 3401 14inch FHD Anti Glare 2 Side ...
16  HP 15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD...
17  Dell Inspiron 3501 15.6" FHD AG Display Laptop...
18  Lenovo Ideapad S145 AMD Ryzen 3 3200U 15.6 inc...
19  HP 15 AMD Athlon 15.6-inch HD Laptop (Silver-3...
20  (Renewed) Dell Inspiron 5509 Laptop|i5-1135G7|...
21  (Renewed) Dell Inspiron 5491 2-in-1 Laptop|i3-...
22  (Renewed) Dell Vostro 5401 Laptop|i5-1035G1|8G...
23  (Renewed) Dell G3 3500 Laptop|i5-10300H|8GB DD...
24  HP 15 Entry Level 15.6-inch HD Laptop (AMD 302...
25  Dell Inspiron 3502 15.6" HD Display Laptop (Pe...
26  Lenovo IdeaPad Slim 3 Intel Celeron N4020 15.6...
27  Lenovo Ideapad Slim 3 AMD Athlon Silver 3050U ...
28  ASUS VivoBook 14 (2020) Intel Quad Core Pentiu...
29  AVITA Essential NE14A2INC433-MB 14-inch Laptop...
30  HP 15 Intel Pentium Gold 6405U Processor Entry...
31  HP Chromebook 14a-na0003TU 14-inch Thin & Ligh...
32  (Renewed) Dell G3 3590 Laptop|i5-9300H|8GB DDR...
33  (Renewed) Dell Inspiron 5593 Laptop|i5-1035G1|...
34  Life Digital Entry Level Laptop, (Intel Core i...
35  Lenovo IdeaPad S540 10th Gen Intel Core i5 15....
36  HP 15 Thin & Light Ryzen 3-3250 Laptop, 4 GB R...
37  Dell Vostro 3401 14inch FHD Anti Glare 2 Side ...
38  HP 15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD...
39  Dell Inspiron 3501 15.6" FHD AG Display Laptop...

In [35]:
# new data frame with split value columns
new = data["Brand_Name"].str.split(" ", n = 1, expand = True)
new

            0                                                  1
0   (Renewed)  Dell Vostro 5401 Laptop|i5-1035G1|8GB DDR4|512...
1   (Renewed)  Dell G3 3500 Laptop|i5-10300H|8GB DDR4|1TB HDD...
2          HP  15 Entry Level 15.6-inch HD Laptop (AMD 3020e/...
3        Dell  Inspiron 3502 15.6" HD Display Laptop (Pentium...
4      Lenovo  IdeaPad Slim 3 Intel Celeron N4020 15.6-inch H...
5      Lenovo  Ideapad Slim 3 AMD Athlon Silver 3050U 15.6 in...
6        ASUS  VivoBook 14 (2020) Intel Quad Core Pentium Sil...
7       AVITA  Essential NE14A2INC433-MB 14-inch Laptop (Cele...
8          HP  15 Intel Pentium Gold 6405U Processor Entry Le...
9          HP  Chromebook 14a-na0003TU 14-inch Thin & Light T...
10  (Renewed)  Dell G3 3590 Laptop|i5-9300H|8GB DDR4|512GB SS...
11  (Renewed)  Dell Inspiron 5593 Laptop|i5-1035G1|8GB DDR4|5...
12       Life  Digital Entry Level Laptop, (Intel Core i3/4GB...
13     Lenovo  IdeaPad S540 10th Gen Intel Core i5 15.6 inch ...
14         HP  15 Thin & Light Ryzen 3-3250 Laptop, 4 GB RAM,...
15       Dell  Vostro 3401 14inch FHD Anti Glare 2 Side Narro...
16         HP  15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD La...
17       Dell  Inspiron 3501 15.6" FHD AG Display Laptop (i3-...
18     Lenovo  Ideapad S145 AMD Ryzen 3 3200U 15.6 inch Full ...
19         HP  15 AMD Athlon 15.6-inch HD Laptop (Silver-3050...
20  (Renewed)  Dell Inspiron 5509 Laptop|i5-1135G7|8GB DDR4|5...
21  (Renewed)  Dell Inspiron 5491 2-in-1 Laptop|i3-10110U|4GB...
22  (Renewed)  Dell Vostro 5401 Laptop|i5-1035G1|8GB DDR4|512...
23  (Renewed)  Dell G3 3500 Laptop|i5-10300H|8GB DDR4|1TB HDD...
24         HP  15 Entry Level 15.6-inch HD Laptop (AMD 3020e/...
25       Dell  Inspiron 3502 15.6" HD Display Laptop (Pentium...
26     Lenovo  IdeaPad Slim 3 Intel Celeron N4020 15.6-inch H...
27     Lenovo  Ideapad Slim 3 AMD Athlon Silver 3050U 15.6 in...
28       ASUS  VivoBook 14 (2020) Intel Quad Core Pentium Sil...
29      AVITA  Essential NE14A2INC433-MB 14-inch Laptop (Cele...
30         HP  15 Intel Pentium Gold 6405U Processor Entry Le...
31         HP  Chromebook 14a-na0003TU 14-inch Thin & Light T...
32  (Renewed)  Dell G3 3590 Laptop|i5-9300H|8GB DDR4|512GB SS...
33  (Renewed)  Dell Inspiron 5593 Laptop|i5-1035G1|8GB DDR4|5...
34       Life  Digital Entry Level Laptop, (Intel Core i3/4GB...
35     Lenovo  IdeaPad S540 10th Gen Intel Core i5 15.6 inch ...
36         HP  15 Thin & Light Ryzen 3-3250 Laptop, 4 GB RAM,...
37       Dell  Vostro 3401 14inch FHD Anti Glare 2 Side Narro...
38         HP  15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD La...
39       Dell  Inspiron 3501 15.6" FHD AG Display Laptop (i3-...

In [36]:
df1 = new.rename(columns={0:"Brand_Name",1:"Product Description"})
df1

   Brand_Name                                Product Description
0   (Renewed)  Dell Vostro 5401 Laptop|i5-1035G1|8GB DDR4|512...
1   (Renewed)  Dell G3 3500 Laptop|i5-10300H|8GB DDR4|1TB HDD...
2          HP  15 Entry Level 15.6-inch HD Laptop (AMD 3020e/...
3        Dell  Inspiron 3502 15.6" HD Display Laptop (Pentium...
4      Lenovo  IdeaPad Slim 3 Intel Celeron N4020 15.6-inch H...
5      Lenovo  Ideapad Slim 3 AMD Athlon Silver 3050U 15.6 in...
6        ASUS  VivoBook 14 (2020) Intel Quad Core Pentium Sil...
7       AVITA  Essential NE14A2INC433-MB 14-inch Laptop (Cele...
8          HP  15 Intel Pentium Gold 6405U Processor Entry Le...
9          HP  Chromebook 14a-na0003TU 14-inch Thin & Light T...
10  (Renewed)  Dell G3 3590 Laptop|i5-9300H|8GB DDR4|512GB SS...
11  (Renewed)  Dell Inspiron 5593 Laptop|i5-1035G1|8GB DDR4|5...
12       Life  Digital Entry Level Laptop, (Intel Core i3/4GB...
13     Lenovo  IdeaPad S540 10th Gen Intel Core i5 15.6 inch ...
14         HP  15 Thin & Light Ryzen 3-3250 Laptop, 4 GB RAM,...
15       Dell  Vostro 3401 14inch FHD Anti Glare 2 Side Narro...
16         HP  15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD La...
17       Dell  Inspiron 3501 15.6" FHD AG Display Laptop (i3-...
18     Lenovo  Ideapad S145 AMD Ryzen 3 3200U 15.6 inch Full ...
19         HP  15 AMD Athlon 15.6-inch HD Laptop (Silver-3050...
20  (Renewed)  Dell Inspiron 5509 Laptop|i5-1135G7|8GB DDR4|5...
21  (Renewed)  Dell Inspiron 5491 2-in-1 Laptop|i3-10110U|4GB...
22  (Renewed)  Dell Vostro 5401 Laptop|i5-1035G1|8GB DDR4|512...
23  (Renewed)  Dell G3 3500 Laptop|i5-10300H|8GB DDR4|1TB HDD...
24         HP  15 Entry Level 15.6-inch HD Laptop (AMD 3020e/...
25       Dell  Inspiron 3502 15.6" HD Display Laptop (Pentium...
26     Lenovo  IdeaPad Slim 3 Intel Celeron N4020 15.6-inch H...
27     Lenovo  Ideapad Slim 3 AMD Athlon Silver 3050U 15.6 in...
28       ASUS  VivoBook 14 (2020) Intel Quad Core Pentium Sil...
29      AVITA  Essential NE14A2INC433-MB 14-inch Laptop (Cele...
30         HP  15 Intel Pentium Gold 6405U Processor Entry Le...
31         HP  Chromebook 14a-na0003TU 14-inch Thin & Light T...
32  (Renewed)  Dell G3 3590 Laptop|i5-9300H|8GB DDR4|512GB SS...
33  (Renewed)  Dell Inspiron 5593 Laptop|i5-1035G1|8GB DDR4|5...
34       Life  Digital Entry Level Laptop, (Intel Core i3/4GB...
35     Lenovo  IdeaPad S540 10th Gen Intel Core i5 15.6 inch ...
36         HP  15 Thin & Light Ryzen 3-3250 Laptop, 4 GB RAM,...
37       Dell  Vostro 3401 14inch FHD Anti Glare 2 Side Narro...
38         HP  15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD La...
39       Dell  Inspiron 3501 15.6" FHD AG Display Laptop (i3-...

In [41]:
#locating Ratings
urls=driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")#collecting urls of all the laptop
UR=[]

for i in urls[:40]:
    UR.append(i.get_attribute('href'))#getting the url of first 10 laptops
    
for url in UR:#loop for every laptop in the list
    driver.get(url)
    
    try:
        available=driver.find_element_by_xpath("//span[@class='a-size-medium a-color-success']")#locating the rating
        Availability.append(available.text)#appending the ratings in Ratings list
        
    except NoSuchElementException   as e:
        Availability.append("NO rating")#appending the No rating if no rating is there

In [54]:
#locating Ratings
urls=driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")#collecting urls of all the laptop
UR=[]
for i in urls[:100]:
    UR.append(i.get_attribute('href'))#getting the url of first 40 laptops
for url in UR:#loop for every laptop in the list
    driver.get(url)
    try:                  #exception handling for nosuchelementexception
        rate=driver.find_element_by_xpath("//span[@id='acrCustomerReviewText']")#locating the ratingd link
        rate.click()                                                      #click the rating link found
        rating=driver.find_element_by_xpath("//span[@class='a-size-medium a-color-base']")#locating the rating
        Ratings.append(rating.text)#appending the ratings in Ratings list
        
    except NoSuchElementException   as e:
        Ratings.append("NO rating")#appending the No rating if no rating is there

In [57]:
Q1 = pd.concat([df1, df, data], axis=1)
Q1

,Brand_Name,Product Description,Price,Ratings,No_of_Ratings,Expected_Delivery,Availability
0,(Renewed),Dell Vostro 5401 Laptop|i5-1035G1|8GB DDR4|512...,"54,990",NO rating,429,"Wednesday, May 5",Only 1 left in stock.
1,(Renewed),Dell G3 3500 Laptop|i5-10300H|8GB DDR4|1TB HDD...,"63,990",4.3 out of 5,1,"Friday, May 7",Only 1 left in stock.
2,HP,15 Entry Level 15.6-inch HD Laptop (AMD 3020e/...,"23,990",4.3 out of 5,104,"Wednesday, May 5",In stock.
3,Dell,"Inspiron 3502 15.6"" HD Display Laptop (Pentium...","27,390",3.5 out of 5,292,"Friday, May 7",In stock.
4,Lenovo,IdeaPad Slim 3 Intel Celeron N4020 15.6-inch H...,"27,890",3.5 out of 5,20,"Saturday, April 24",Only 1 left in stock.
5,Lenovo,Ideapad Slim 3 AMD Athlon Silver 3050U 15.6 in...,"25,990",NO rating,453,"Friday, April 23",In stock.
6,ASUS,VivoBook 14 (2020) Intel Quad Core Pentium Sil...,"24,990",NO rating,163,"Tuesday, April 27",Only 2 left in stock.
7,AVITA,Essential NE14A2INC433-MB 14-inch Laptop (Cele...,"17,990",NO rating,179,"Sunday, April 25",In stock.
8,HP,15 Intel Pentium Gold 6405U Processor Entry Le...,"26,599",NO rating,5,"Saturday, April 24",In stock.
9,HP,Chromebook 14a-na0003TU 14-inch Thin & Light T...,"24,990",NO rating,38,"Friday, April 23",In stock.
10,(Renewed),Dell G3 3590 Laptop|i5-9300H|8GB DDR4|512GB SS...,"61,990",NO rating,144,"Friday, April 23",In stock.
11,(Renewed),Dell Inspiron 5593 Laptop|i5-1035G1|8GB DDR4|5...,"53,990",NO rating,"1,275","Wednesday, May 5",Only 1 left in stock.
12,Life,"Digital Entry Level Laptop, (Intel Core i3/4GB...","21,990",NO rating,4,"Friday, May 7",In stock.
13,Lenovo,IdeaPad S540 10th Gen Intel Core i5 15.6 inch ...,"60,990",NO rating,73,"Wednesday, May 5",In stock.
14,HP,"15 Thin & Light Ryzen 3-3250 Laptop, 4 GB RAM,...","31,999",NO rating,7,"Friday, May 7",In stock.
15,Dell,Vostro 3401 14inch FHD Anti Glare 2 Side Narro...,"35,390",NO rating,429,"Friday, April 23",In stock.
16,HP,15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD La...,"46,494",NO rating,1,"Sunday, April 25",In stock.
17,Dell,"Inspiron 3501 15.6"" FHD AG Display Laptop (i3-...","38,790",NO rating,104,"Tuesday, April 27",In stock.
18,Lenovo,Ideapad S145 AMD Ryzen 3 3200U 15.6 inch Full ...,"27,990",NO rating,292,"Saturday, April 24",In stock.
19,HP,15 AMD Athlon 15.6-inch HD Laptop (Silver-3050...,"26,990",NO rating,20,"Friday, April 23",In stock.
20,(Renewed),Dell Inspiron 5509 Laptop|i5-1135G7|8GB DDR4|5...,"55,990",NO rating,453,"Friday, April 23",Only 1 left in stock.
21,(Renewed),Dell Inspiron 5491 2-in-1 Laptop|i3-10110U|4GB...,"42,990",4.3 out of 5,163,"Friday, April 23",Only 1 left in stock.
22,(Renewed),Dell Vostro 5401 Laptop|i5-1035G1|8GB DDR4|512...,"54,990",4.3 out of 5,179,"Friday, April 23",Only 1 left in stock.
23,(Renewed),Dell G3 3500 Laptop|i5-10300H|8GB DDR4|1TB HDD...,"63,990",4.4 out of 5,5,"Wednesday, May 5",Only 1 left in stock.
24,HP,15 Entry Level 15.6-inch HD Laptop (AMD 3020e/...,"23,990",4.4 out of 5,38,"Friday, May 7",In stock.
25,Dell,"Inspiron 3502 15.6"" HD Display Laptop (Pentium...","27,390",4.5 out of 5,144,"Wednesday, May 5",In stock.
26,Lenovo,IdeaPad Slim 3 Intel Celeron N4020 15.6-inch H...,"27,890",4.5 out of 5,"1,275","Friday, May 7",Only 1 left in stock.
27,Lenovo,Ideapad Slim 3 AMD Athlon Silver 3050U 15.6 in...,"25,990",4.2 out of 5,4,"Wednesday, May 5",In stock.
28,ASUS,VivoBook 14 (2020) Intel Quad Core Pentium Sil...,"24,990",4.2 out of 5,73,"Friday, May 7",Only 2 left in stock.
29,AVITA,Essential NE14A2INC433-MB 14-inch Laptop (Cele...,"17,990",4.4 out of 5,7,"Wednesday, May 5",In stock.
30,HP,15 Intel Pentium Gold 6405U Processor Entry Le...,"26,599",4.4 out of 5,429,"Friday, May 7",In stock.
31,HP,Chromebook 14a-na0003TU 14-inch Thin & Light T...,"24,990",4.2 out of 5,1,"Saturday, April 24",In stock.
32,(Renewed),Dell G3 3590 Laptop|i5-9300H|8GB DDR4|512GB SS...,"61,990",4.2 out of 5,104,"Friday, April 23",In stock.
33,(Renewed),Dell Inspiron 5593 Laptop|i5-1035G1|8GB DDR4|5...,"53,990",4.4 out of 5,292,"Tuesday, April 27",Only 1 left in stock.
34,Life,"Digital Entry Level Laptop, (Intel Core i3/4GB...","21,990",4.4 out of 5,20,"Sunday, April 25",In stock.
35,Lenovo,IdeaPad S540 10th Gen Intel Core i5 15.6 inch ...,"60,990",4 out of 5,453,"Saturday, April 24",In stock.
36,HP,"15 Thin & Light Ryzen 3-3250 Laptop, 4 GB RAM,...","31,999",4 out of 5,163,"Friday, April 23",In stock.
37,Dell,Vostro 3401 14inch FHD Anti Glare 2 Side Narro...,"35,390",4.3 out of 5,179,"Friday, April 23",In stock.
38,HP,15 Ryzen 5 Processor 15.6-inch(39.6 cm) FHD La...,"46,494",4.3 out of 5,5,"Wednesday, May 5",In stock.
39,Dell,"Inspiron 3501 15.6"" FHD AG Display Laptop (i3-...","38,790",4 out of 5,38,"Friday, May 7",In stock.

Write a python program to access the search bar and search button on images.google.com and 
scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’

In [61]:
url = 'https://images.google.com/?gws_rd=ssl' 

driver.get(url)

In [64]:
#entering Inputs in the feild

search_product = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/form/div[1]/div[1]/div[1]/div/div[2]/input").send_keys("fruits")
search_btn = driver.find_element_by_xpath("//span[@class='z1asCe MZy1Rb']").click()

In [61]:
from bs4 import BeautifulSoup
import requests

In [64]:
#Firstly, set search_words which you want to have the image of
search_words = ['Fruits', 'Cars', 'Machine Learning']



#Specify the path where you want to download to
img_dir = 'C:/Users/shaik mahaboob basha/Downloads/Web Scraping Images'

import os

#Repeat extracting for every words
for word in search_words:
    dir_path = img_dir + word
if not os.path.exists(dir_path):
    os.makedirs(dir_path)
    
    #Make word suitable for URL
    urlKeyword = parse.quote(word)
    
    
    #Create url with target word
    url = 'https://www.google.com/search?hl=jp&q=' + urlKeyword + "btnG=Google+Search&tbs=0&safe=off&tbm=isch"
    
    #Request is made with url and headers
    request = req.Request(url=url, headers=headers)
    page = req.urlopen(request)


     #page that you reveived into utf-8
    html = page.read().decode('utf-8')


    html = bs4.BeautifulSoup(html, 'html.parser')
    
    #.rg_meta.notranslate is for extracting data without permission(not sure)
    elems = html.select('.rg_meta.notranslate')
    counter = 0
    error_counter = 0

    for ele in elems:
        ele = ele.contents[0].replace(",").split(',')
        eledict = dict()
    
    #imageURL is indicated here.
    for e in ele:
        num = e.find(':')
        eledict[e[0:num]] = e[num+1:]
        imageURL = eledict['ou']
        
        try:
            file_path = dir_path + '/' + str(counter)+".jpg"
            urlretrieve(imageURL, file_path)
            counter += 1
            
        except Exception as e:
            error_counter += 1
            if counter == 1:
                print('Start downloading', word)
                if counter==100:
                    break
                    print("{} errors occur out of ".format(counter, error_counter))

Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on 
www.flipkart.com and scrape following details for all the search results displayed on 1st page. 
Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, 
“Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display 
Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”. 
Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe 
and CSV.

In [6]:
url = 'https://www.flipkart.com' 

driver.get(url)

In [7]:
#entering Inputs in the feild

close_btn = driver.find_element_by_xpath('/html/body/div[2]/div/div/button').click()

search_product = driver.find_element_by_xpath("/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input").send_keys("Smartphone")
search_btn = driver.find_element_by_class_name('_34RNph').click()

In [9]:
#creating the empty list
Brand_Name=[]
Name_of_the_Product=[]
Colour = []
Ram = []
Storage = []
Primary_Camera = []
Secoundary_Camera = []
Display_Size = []
Processor = []
Battery_Capacity = []
Ratings=[]
Price=[]
Product_URL=[]

In [10]:
#Scrapping Titles
titles=driver.find_elements_by_xpath("//div[@class='_4rR01T']")
for i in titles[:30]:
    Brand_Name.append(i.text)

In [11]:
data=pd.DataFrame({'Brand_Name':Brand_Name[:30]})
print(data)

                               Brand_Name
0          REDMI 9i (Nature Green, 64 GB)
1        REDMI 9i (Midnight Black, 64 GB)
2           realme C20 (Cool Grey, 32 GB)
3                 Nokia 5.4 (Dusk, 64 GB)
4           realme C20 (Cool Blue, 32 GB)
5              REDMI 9i (Sea Blue, 64 GB)
6                  OPPO A12 (Blue, 64 GB)
7              POCO M3 (Cool Blue, 64 GB)
8             OPPO A12 (Deep Blue, 32 GB)
9             OPPO A12 (Deep Blue, 64 GB)
10                 OPPO A12 (Blue, 32 GB)
11                OPPO A12 (Black, 32 GB)
12            POCO M3 (Cool Blue, 128 GB)
13          Nokia C3 (Nordic Blue, 32 GB)
14       OPPO A12 (Flowing Silver, 32 GB)
15                POCO M3 (Yellow, 64 GB)
16       realme C12 (Power Silver, 32 GB)
17         realme C12 (Power Blue, 32 GB)
18          POCO M3 (Power Black, 128 GB)
19          Nokia 2.4 (Fjord Blue, 64 GB)
20  realme Narzo 30A (Laser Black, 64 GB)
21  realme Narzo 30A (Laser Black, 32 GB)
22           POCO M3 (Power Black, 64 GB)
23                 Nokia C3 (Sand, 16 GB)

In [12]:
# new data frame with split value columns
new = data["Brand_Name"].str.split(" ", n = 1, expand = True)
new

         0                               1
0    REDMI        9i (Nature Green, 64 GB)
1    REDMI      9i (Midnight Black, 64 GB)
2   realme          C20 (Cool Grey, 32 GB)
3    Nokia               5.4 (Dusk, 64 GB)
4   realme          C20 (Cool Blue, 32 GB)
5    REDMI            9i (Sea Blue, 64 GB)
6     OPPO               A12 (Blue, 64 GB)
7     POCO           M3 (Cool Blue, 64 GB)
8     OPPO          A12 (Deep Blue, 32 GB)
9     OPPO          A12 (Deep Blue, 64 GB)
10    OPPO               A12 (Blue, 32 GB)
11    OPPO              A12 (Black, 32 GB)
12    POCO          M3 (Cool Blue, 128 GB)
13   Nokia         C3 (Nordic Blue, 32 GB)
14    OPPO     A12 (Flowing Silver, 32 GB)
15    POCO              M3 (Yellow, 64 GB)
16  realme       C12 (Power Silver, 32 GB)
17  realme         C12 (Power Blue, 32 GB)
18    POCO        M3 (Power Black, 128 GB)
19   Nokia         2.4 (Fjord Blue, 64 GB)
20  realme  Narzo 30A (Laser Black, 64 GB)
21  realme  Narzo 30A (Laser Black, 32 GB)
22    POCO         M3 (Power Black, 64 GB)
23   Nokia                C3 (Sand, 16 GB)

In [30]:
df2 = new.rename(columns={0:"Brand_Name",1:"Product_Description"})
Brand = df2.drop(['Product_Description'],axis = 1)

In [15]:
# new data frame with split value columns
new2 = df2["Product_Description"].str.split(r'[\:\-\(\)]+', n = 1, expand = True)
new2

             0                       1
0          9i     Nature Green, 64 GB)
1          9i   Midnight Black, 64 GB)
2         C20        Cool Grey, 32 GB)
3         5.4             Dusk, 64 GB)
4         C20        Cool Blue, 32 GB)
5          9i         Sea Blue, 64 GB)
6         A12             Blue, 64 GB)
7          M3        Cool Blue, 64 GB)
8         A12        Deep Blue, 32 GB)
9         A12        Deep Blue, 64 GB)
10        A12             Blue, 32 GB)
11        A12            Black, 32 GB)
12         M3       Cool Blue, 128 GB)
13         C3      Nordic Blue, 32 GB)
14        A12   Flowing Silver, 32 GB)
15         M3           Yellow, 64 GB)
16        C12     Power Silver, 32 GB)
17        C12       Power Blue, 32 GB)
18         M3     Power Black, 128 GB)
19        2.4       Fjord Blue, 64 GB)
20  Narzo 30A      Laser Black, 64 GB)
21  Narzo 30A      Laser Black, 32 GB)
22         M3      Power Black, 64 GB)
23         C3             Sand, 16 GB)

In [32]:
df4 = new2.rename(columns={0:"Model",1:"Product_Details"})
model = df4.drop(['Product_Details'],axis = 1)
model

         Model
0          9i
1          9i
2         C20
3         5.4
4         C20
5          9i
6         A12
7          M3
8         A12
9         A12
10        A12
11        A12
12         M3
13         C3
14        A12
15         M3
16        C12
17        C12
18         M3
19        2.4
20  Narzo 30A
21  Narzo 30A
22         M3
23         C3

In [18]:
# new data frame with split value columns
new3 = df4["Product_Details"].str.split(r'[\:\-\(\),]+', n = 1, expand = True)
new3

                 0         1
0     Nature Green    64 GB)
1   Midnight Black    64 GB)
2        Cool Grey    32 GB)
3             Dusk    64 GB)
4        Cool Blue    32 GB)
5         Sea Blue    64 GB)
6             Blue    64 GB)
7        Cool Blue    64 GB)
8        Deep Blue    32 GB)
9        Deep Blue    64 GB)
10            Blue    32 GB)
11           Black    32 GB)
12       Cool Blue   128 GB)
13     Nordic Blue    32 GB)
14  Flowing Silver    32 GB)
15          Yellow    64 GB)
16    Power Silver    32 GB)
17      Power Blue    32 GB)
18     Power Black   128 GB)
19      Fjord Blue    64 GB)
20     Laser Black    64 GB)
21     Laser Black    32 GB)
22     Power Black    64 GB)
23            Sand    16 GB)

In [19]:
df6 = new3.rename(columns={0:"Colour",1:"Storage_Details"})
df6

            Colour Storage_Details
0     Nature Green          64 GB)
1   Midnight Black          64 GB)
2        Cool Grey          32 GB)
3             Dusk          64 GB)
4        Cool Blue          32 GB)
5         Sea Blue          64 GB)
6             Blue          64 GB)
7        Cool Blue          64 GB)
8        Deep Blue          32 GB)
9        Deep Blue          64 GB)
10            Blue          32 GB)
11           Black          32 GB)
12       Cool Blue         128 GB)
13     Nordic Blue          32 GB)
14  Flowing Silver          32 GB)
15          Yellow          64 GB)
16    Power Silver          32 GB)
17      Power Blue          32 GB)
18     Power Black         128 GB)
19      Fjord Blue          64 GB)
20     Laser Black          64 GB)
21     Laser Black          32 GB)
22     Power Black          64 GB)
23            Sand          16 GB)

In [21]:
df6['Storage_Details'] = df6['Storage_Details'].str.replace(')',' ')
df6

            Colour Storage_Details
0     Nature Green          64 GB
1   Midnight Black          64 GB
2        Cool Grey          32 GB
3             Dusk          64 GB
4        Cool Blue          32 GB
5         Sea Blue          64 GB
6             Blue          64 GB
7        Cool Blue          64 GB
8        Deep Blue          32 GB
9        Deep Blue          64 GB
10            Blue          32 GB
11           Black          32 GB
12       Cool Blue         128 GB
13     Nordic Blue          32 GB
14  Flowing Silver          32 GB
15          Yellow          64 GB
16    Power Silver          32 GB
17      Power Blue          32 GB
18     Power Black         128 GB
19      Fjord Blue          64 GB
20     Laser Black          64 GB
21     Laser Black          32 GB
22     Power Black          64 GB
23            Sand          16 GB

In [35]:
#scrapping Price
prices=driver.find_elements_by_xpath("//div[@class='_30jeq3 _1_WHN1']")
for i in prices[:30]:
    Price.append(i.text)

In [38]:
p1=pd.DataFrame({'Price':Price[:30]})
print(p1)

      Price
0    ₹7,999
1    ₹7,999
2    ₹6,799
3   ₹15,499
4    ₹6,799
5    ₹7,999
6    ₹8,990
7   ₹10,999
8    ₹7,990
9    ₹8,990
10   ₹7,990
11   ₹7,990
12  ₹11,999
13   ₹6,599
14   ₹7,990
15  ₹10,999
16   ₹7,999
17   ₹7,999
18  ₹11,999
19  ₹10,399
20   ₹9,499
21   ₹8,499
22  ₹10,999
23   ₹7,199

In [42]:
#scrapping Price
rating=driver.find_elements_by_xpath("//span[@id='productRating_LSTMOBFV8RYNA4FVEH7NNKUZA_MOBFV8RYNA4FVEH7_']")
for i in rating[:30]:
    Ratings.append(i.text)

In [45]:
R1=pd.DataFrame({'Ratings':Ratings[:24]})
print(R1)

   Ratings
0      4.3
1      4.3
2      4.6
3      3.9
4      4.6
5      4.3
6      4.4
7      4.3
8      4.3
9      4.4
10     4.3
11     4.3
12     4.3
13     3.8
14     4.3
15     4.3
16     4.4
17     4.4
18     4.3
19     4.1
20     4.4
21     4.4
22     4.3
23     3.9

In [46]:
Q3 = pd.concat([Brand, model, df6, p1, R1], axis=1)
Q3

   Brand_Name       Model          Colour Storage_Details    Price Ratings
0       REDMI         9i     Nature Green          64 GB    ₹7,999     4.3
1       REDMI         9i   Midnight Black          64 GB    ₹7,999     4.3
2      realme        C20        Cool Grey          32 GB    ₹6,799     4.6
3       Nokia        5.4             Dusk          64 GB   ₹15,499     3.9
4      realme        C20        Cool Blue          32 GB    ₹6,799     4.6
5       REDMI         9i         Sea Blue          64 GB    ₹7,999     4.3
6        OPPO        A12             Blue          64 GB    ₹8,990     4.4
7        POCO         M3        Cool Blue          64 GB   ₹10,999     4.3
8        OPPO        A12        Deep Blue          32 GB    ₹7,990     4.3
9        OPPO        A12        Deep Blue          64 GB    ₹8,990     4.4
10       OPPO        A12             Blue          32 GB    ₹7,990     4.3
11       OPPO        A12            Black          32 GB    ₹7,990     4.3
12       POCO         M3        Cool Blue         128 GB   ₹11,999     4.3
13      Nokia         C3      Nordic Blue          32 GB    ₹6,599     3.8
14       OPPO        A12   Flowing Silver          32 GB    ₹7,990     4.3
15       POCO         M3           Yellow          64 GB   ₹10,999     4.3
16     realme        C12     Power Silver          32 GB    ₹7,999     4.4
17     realme        C12       Power Blue          32 GB    ₹7,999     4.4
18       POCO         M3      Power Black         128 GB   ₹11,999     4.3
19      Nokia        2.4       Fjord Blue          64 GB   ₹10,399     4.1
20     realme  Narzo 30A      Laser Black          64 GB    ₹9,499     4.4
21     realme  Narzo 30A      Laser Black          32 GB    ₹8,499     4.4
22       POCO         M3      Power Black          64 GB   ₹10,999     4.3
23      Nokia         C3             Sand          16 GB    ₹7,199     3.9

In [59]:
# saving the dataframe
Q3.to_csv('smartphone.csv')

Q7.Write a program to scrap all the available details of top 10 gaming laptops from digit.in.

In [4]:
url = 'https://www.digit.in/' 

driver.get(url)

In [5]:
#entering Inputs in the feild

search_btn = driver.find_element_by_xpath("/html/body/div[3]/div/div[2]/div[2]/div[4]/ul/li[9]/a").click()

In [6]:
Heading_title=[]
Display = []
Graphic = []
Dimension = []
Weight = []
Processor = []
OS = []
HDD = []
RAM = []

In [7]:
# Scraping the RAM and HDD Data

memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[6]/td[1]")#list of specificaion name
memories_spec=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[6]/td[3]")#values of specifiations 
for i in range(len(memories)):
        if memories[i].text=='Memory':
            HDD.append(memories_spec[i].text.split('/')[0])
            RAM.append(memories_spec[i].text.split('/')[1])
        else:
            HDD.append('No details available')#append no details as value for memory is missing in some of the laptops
            RAM.append('No details available')#append no details as value for memory is missing in some of the laptops

In [8]:
#scraping the product

product_name=driver.find_elements_by_xpath("//div[@class='TopNumbeHeading active sticky-footer']")
for i in product_name:
    if i.text is None :
        Heading_title.append("--") 
    else:
        Heading_title.append(i.text)
    
Heading_title

['1.\nMSI GT76 TITAN DT 9SG',
 '2.\nALIENWARE 17 AREA-51M',
 '3.\nHP OMEN 15 2020',
 '4.\nASUS ZEPHYRUS G14',
 '5.\nLENOVO LEGION Y540',
 '6.\nASUS ROG ZEPHYRUS G GA502',
 '7.\nASUS ROG ZEPHYRUS S GX531',
 '8.\nMSI GT83VR 7RE TITAN SLI',
 '9.\nASUS ROG ZEPHYRUS DUO 15',
 '10.\nDELL G3']

In [11]:
df=pd.DataFrame({'Heading_title':Heading_title})

new = df["Heading_title"].str.split("\n", n = 1, expand = True)
df2 = new.rename(columns={0:"S.No",1:"Model_Name"})
Brand = df2.drop(['S.No'],axis = 1)
Brand

                  Model_Name
0      MSI GT76 TITAN DT 9SG
1      ALIENWARE 17 AREA-51M
2            HP OMEN 15 2020
3          ASUS ZEPHYRUS G14
4         LENOVO LEGION Y540
5  ASUS ROG ZEPHYRUS G GA502
6  ASUS ROG ZEPHYRUS S GX531
7   MSI GT83VR 7RE TITAN SLI
8   ASUS ROG ZEPHYRUS DUO 15
9                    DELL G3

In [12]:
#scraping the Display


memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[4]/td[1]")#list of specificaion name
memories_spec=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[4]/td[3]")#values of specifiations 
for i in range(len(memories)):
        if memories[i].text=='Display':
            
            Display.append(memories_spec[i].text)
        else:
            
            Display.append('No details available')#append no details as value for memory is missing in some of the laptops

In [13]:
#Scraping the Graphic


memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[9]/td[1]")#list of specificaion name
memories_spec=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[9]/td[3]")#values of specifiations 
for i in range(len(memories)):
        if memories[i].text=='Graphics Processor':
            
            Graphic.append(memories_spec[i].text)
        else:
            
            Graphic.append('No details available')#append no details as value for memory is missing in some of the laptops

In [14]:
#Scraping the Dimension

memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[8]/td[1]")#list of specificaion name
memories_spec=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[8]/td[3]")#values of specifiations 
for i in range(len(memories)):
        if memories[i].text=='Dimension':
            
            Dimension.append(memories_spec[i].text)
        else:
            
            Dimension.append('No details available')#append no details as value for memory is missing in some of the laptops

In [15]:
#Scraping the Weight

memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[7]/td[1]")#list of specificaion name
memories_spec=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[7]/td[3]")#values of specifiations 
for i in range(len(memories)):
        if memories[i].text=='Weight':
            
            Weight.append(memories_spec[i].text)
        else:
            
            Weight.append('No details available')#append no details as value for memory is missing in some of the laptops

In [16]:
#Scraping the Processor

memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[5]/td[1]")#list of specificaion name
memories_spec=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[5]/td[3]")#values of specifiations 
for i in range(len(memories)):
        if memories[i].text=='Processor':
            
            Processor.append(memories_spec[i].text)
        else:
            
            Processor.append('No details available')#append no details as value for memory is missing in some of the laptops

In [17]:
#Scraping the OS

memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[3]/td[1]")#list of specificaion name
memories_spec=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[3]/td[3]")#values of specifiations 
for i in range(len(memories)):
        if memories[i].text=='OS':
            
            OS.append(memories_spec[i].text)
        else:
            
            OS.append('No details available')#append no details as value for memory is missing in some of the laptops

In [22]:
R1=pd.DataFrame({'OS':OS,'Display':Display,'Processor':Processor,'RAM':RAM,'HDD':HDD,'Weight':Weight,'Dimension':Dimension,'Graphic':Graphic})

In [21]:
Q7 = pd.concat([Brand, R1], axis=1)
Q7

,Model_Name,OS,Display,Processor,RAM,HDD,Weight,Dimension,Graphic
0,MSI GT76 TITAN DT 9SG,Windows 10 Pro,"17.3"" (UHD 3840x2160)",Intel 9th Gen Core i9-9900K | 5000 MHz,64 GBGB DDR4,1 TB HDD,4.2 kg,397 x 330 x 33~42 mm,NVIDIA GeForce RTX 2080
1,ALIENWARE 17 AREA-51M,Windows 10 Pro,"17.3"" (FHD (1920 x 1080))",Intel 9th Gen Core i9-9900K | 5000 MHz,32GB DDR4,1 TB PCIe SSD,3.87 Kg,42 mm x 402.6 mm x 319.14 mm,NVIDIA GeForce RTX 2080
2,HP OMEN 15 2020,Windows 10 Home,"15.6"" (1920 x 1080)",Intel i7-10750H 10th Gen | 1.6GHz,16 GBGB DDR4,512 GB SSD,5.40,14.09 x 9.44 x 0.89,Nvidia GeForce GTX 1650Ti
3,ASUS ZEPHYRUS G14,Windows 10 Home,"14"" (1920 x 1080)",AMD 3rd Generation Ryzen 9 | 3.3 GHz,16 GBGB DDR4,1 TB SSD,1.65,32.5 x 22.1 x 1.8,NVIDIA GeForce RTX 2060
4,LENOVO LEGION Y540,Windows 10 Home,"15.6"" (1920 X 1080)",9th Generation Core Intel I7-9750H | 2.6 Ghz,8GB DDR4,1 TB SSD,2.3,365mm x 260mm x 25.9mm,NVIDIA® GeForce RTX™ 2060
5,ASUS ROG ZEPHYRUS G GA502,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen 7 Quad Core 3750H | 2.3 GHz,16GB DDR4,512 GB SSD,2.2,360 x 252 x 20.4,NVIDIA Geforce GTX 1660 Ti
6,ASUS ROG ZEPHYRUS S GX531,Windows 10 Home,"15.6"" (1920 X 1080)",9th Gen Intel Core i7-8750H | 2.2 GHz,16 GBGB DDR4,512GB SSD,2.1,360 (W) x 268 (D) x 15.35~16.15 (H) mm,NVIDIA® GeForce RTX™ 2070 (Max-Q)
7,MSI GT83VR 7RE TITAN SLI,Windows 10 Home 64 bit,"18.4"" (1920 x 1080)",Intel CM238 Core i7-7820HK+CM238 7th Gen | 3.5GHz,64GB DDR4,1.5 TB SATA,5.5,458 x 339 x 69,Dual GTX1070
8,ASUS ROG ZEPHYRUS DUO 15,Windows 10,"15.6"" (3840 x 1100)",Intel Core i7 10th Gen 10875H | NA,4 GBGB DDR4,512 GB SSD,2.4,268.30 x 360.00 x 20.90,NVIDIA GeForce RTX 2070 Max-Q
9,DELL G3,Windows 10 Home Plus,15.6 MP | NA,8th Gen Intel core i5-8300H | 2.3GHz,8GB DDR4,1TB HDD,2.53,22.7 X 380 X 258,NVidia GeForce GTX 1050

6. Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 –
September 20) from trak.in

In [3]:
url = 'https://www.trak.in/' 

driver.get(url)

In [4]:
#entering Inputs in the feild

search_btn = driver.find_element_by_xpath("/html/body/div[1]/header/div[2]/div/div/div/div/nav/ul/li[9]").click()

search_btn = driver.find_element_by_xpath("/html/body/div[1]/header/div[2]/div/div/div/div/nav/ul/li[9]/ul/li[1]/a").click()

In [5]:
fund_dict = {}
fund_dict['Date'] = []
fund_dict['Startup Name'] = []
fund_dict['Industry / Vertical'] = []
fund_dict['Sub-Vertical'] = []
fund_dict['Investor Name'] = []
fund_dict['City'] = []
fund_dict['Investment Type'] = []
fund_dict['Amount'] = []

In [6]:
for i in range(48,51):
    driver.find_element_by_xpath('//div[@id="tablepress-{}_wrapper"]/div/label/select/option[4]'.format(i)).click()

    # Date
    dt = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[2]'.format(i))
    for d in dt:
        fund_dict['Date'].append(d.text)

    # Startup Name
    sn = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[3]'.format(i))
    for n in sn:
        fund_dict['Startup Name'].append(n.text)
     
    # Industry / Vertical
    IV = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[4]'.format(i))
    for I in IV:
        fund_dict['Industry / Vertical'].append(I.text)
        
    # Sub-Vertical
    SV = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[5]'.format(i))
    for v in SV:
        fund_dict['Sub-Vertical'].append(v.text)
        
    # City
    C = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[6]'.format(i))
    for l in C:
        fund_dict['City'].append(l.text)
        
    # Investor Name
    IN = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[7]'.format(i))
    for N in IN:
        fund_dict['Investor Name'].append(N.text)
    
    # Investment Type
    IT = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[8]'.format(i))
    for T in IT:
        fund_dict['Investment Type'].append(T.text)
        
    # Amount
    Amounts = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[9]'.format(i))
    for A in Amounts:
        fund_dict['Amount'].append(T.text)
    
    
    
fund_df = pd.DataFrame(fund_dict)
fund_df

,Date,Startup Name,Industry / Vertical,Sub-Vertical,Investor Name,City,Investment Type,Amount
0,15/07/2020,Flipkart,E-commerce,E-commerce,Walmart Inc,Bangalore,M&A,Venture-Series Unknown
1,16/07/2020,Vedantu,EduTech,Online Tutoring,Coatue Management,Bangalore,Series D,Venture-Series Unknown
2,16/07/2020,Crio,EduTech,Learning Platform for Developers,021 Capital,Bangalore,pre-Series A,Venture-Series Unknown
3,14/07/2020,goDutch,FinTech,Group Payments,"Matrix India,Y Combinator, Global Founders Cap...",Mumbai,Seed,Venture-Series Unknown
4,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Recruit Co. Ltd.,Singapore and Bangalore,pre-Series B,Venture-Series Unknown
5,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Adar Poonawalla and Kris Gopalakrishnan.,Pune,Venture-Series Unknown,Venture-Series Unknown
6,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Incubate Fund India and Beyond Next Ventures,Pune,pre-Series A,Venture-Series Unknown
7,15/07/2020,PumPumPum,Automotive Rental,Used Car-leasing platform,Early Adapters Syndicate,Gurgaon,Seed,Venture-Series Unknown
8,14/07/2020,FLYX,OTT Player,Streaming Social Network,"Raj Mishra, founder of AIT Global Inc",New York and Delhi,pre-Seed,Venture-Series Unknown
9,13/07/2020,Open Appliances Pvt. Ltd.,Information Technology,Internet-of-Things Security Solutions,Unicorn India Ventures,Bangalore,Venture-Series Unknown,Venture-Series Unknown
10,15/08/2020,Practo,HealthTech,Health care and Wellness,A1A Company,Bangalore,Series F,Pre-Series A
11,13/08/2020,Medlife,E-commerce,Online Pharmacy,Prasid Uno Family Trust and SC Credit Fund,Bangalore,,Pre-Series A
12,13/08/2020,HungerBox,FoodTech,Online Food Delivery Service,"One97, Sabre Partners Trust, Pratithi Investme...",Bangalore,Series D1,Pre-Series A
13,04/08/2020,Dunzo,Hyper-local Logistics,Online Delivery Services,Existing Backers,Bangalore,In Progress,Pre-Series A
14,11/08/2020,Terra.do,EduTech,"Online Climate School, E-learning","Stanford Angels and Entrepreneurs (India), BEE...","Stanford, California,",Seed,Pre-Series A
15,12/08/2020,Classplus,EduTech,"E-learning, Online Tutoring",Falcon Edge,Noida,In Progress,Pre-Series A
16,14/08/2020,Niyo,FinTech,Financial Services,Niyo Solutions Inc.,Bangalore,,Pre-Series A
17,10/08/2020,ZestMoney,FinTech,Financial Services,Primrose Hills Ventures,Bangalore,,Pre-Series A
18,07/08/2020,FreshToHome,E-commerce,Food Delivery,Ascent Capital,Bangalore,Venture,Pre-Series A
19,13/08/2020,Eduvanz,FinTech,Financial Services,"Sequoia India, Unitus",Mumbai,Series A,Pre-Series A
20,03/08/2020,CrowdPouch,FinTech,Financial Services,Elina Investments Pvt. Ltd,Bangalore,Angel,Pre-Series A
21,04/08/2020,DrinkPrime,Water Purification,Water Purification,"Sequoia Surge, ON Mauritius",Bangalore,Pre-Series A,Pre-Series A
22,08/09/2020,Byju’s,EduTech,Online Tutoring,"Silver Lake, Tiger Global, General Atlantic an...",Bangalore,Private Equity,pre-Series A
23,12/09/2020,mCaffeine,Personal Care,Skincare & Haircare,"Amicus Capital Private Equity I LLP, Amicus Ca...",Mumbai,Series B,pre-Series A
24,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Rainmatter Capital,Bangalore,Angel,pre-Series A
25,02/09/2020,Winzo,Online Gaming,Online Gaming,"Kalaari Capital Partners, IndigoEdge Managemen...",New Delhi,Series B,pre-Series A
26,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Alpha Wave Incubation, Exfinity Venture Partne...","Newark, Delaware, United States of Amercia",Series A,pre-Series A
27,07/09/2020,Melorra,E-commerce,Online Jewelry Store,"Shadow Holdings, Lightbox.",Bangalore,Debt Financing,pre-Series A
28,07/09/2020,1mg,E-commerce,Online Pharmacy,"Gaja Capital, Tata Capital, Partners Group",Gurgaon,In Progress,pre-Series A
29,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Caretech Pte Inc,Bangalore,Series B,pre-Series A
30,31/08/2020,Apna,Human Resources,Recruitment Platform,Lightspeed India and Sequoia Capital India,Bangalore,Series A,pre-Series A
31,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Chiratae Ventures,Mumbai,Seed,pre-Series A
32,08/09/2020,Cell Propulsion,Automobile,Electric Mobility Solutions,growX Ventures and Micelio,Bangalore,pre-Series A,pre-Series A

3. Write a python program to access the search bar and search button on images.google.com and 
scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’.

In [ ]:
#Firstly, set search_words which you want to have the image of
search_words = ['Fruits', 'Cars', 'Machine Learning']

In [7]:
#from selenium import webdriver
#from selenium.webdriver.common.keys import Keys
import time

#driver = webdriver.Chrome('C:/Web Scraping course/chromedriver.exe')
driver.get('https://images.google.com/')

box = driver.find_element_by_xpath("//input[@class='gLFyf gsfi']")
box.send_keys('Fruits')
#box.send_keys(Keys.ENTER).click

titles=driver.find_element_by_xpath("//span[@class='z1asCe MZy1Rb']").click()

In [8]:
import time



#Will keep scrolling down the webpage until it cannot scroll no more
last_height = driver.execute_script('return document.body.scrollHeight')
while True:
    driver.execute_script('window.scrollTo(0,document.body.scrollHeight)')
    time.sleep(2)
    new_height = driver.execute_script('return document.body.scrollHeight')
    try:
        driver.find_element_by_xpath('//*[@id="islmp"]/div/div/div/div/div[5]/input').click()
        time.sleep(2)
    except:
        pass
    if new_height == last_height:
        break
    last_height = new_height


for i in range(1, 10):
    try:
        driver.find_element_by_xpath('//*[@id="islrg"]/div[1]/div['+str(i)+']/a[1]/div[1]/img').screenshot(r'C:\Users\shaik mahaboob basha\Downloads\Web Scraping ImagesMachine Learning ('+str(i)+').png')
    except:
        pass